### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litex-acorn-baseboard#9]
Would you mind adding a license file? Something like CC-BY (permission) or CC-BY-SA (share and share alike) could be a good choice.

**Comment by enjoy-digital** [comment]
Sorry for the delay, done with https://github.com/enjoy-digital/litex-acorn-baseboard/commit/e881d0ef5610f8b88483e3b4aa4f07646c97e48d :)
